### ISSUE TITLE
`place_id` is required in one place, but deprecated in another

### ISSUE THREAD

**Issue by pushkin-** [yvesalexandre/bandicoot#1]
In `bandicoot/io.py` line [383](https://github.com/yvesalexandre/bandicoot/blob/a933fbd383cb7d6151c8a9ddf35ef1d5194efe53/bandicoot/io.py#L383), you use the `place_id` key.

    antennas = dict((d['place_id'], (float(d['latitude']), float(d['longitude'])))

On line [118](https://github.com/yvesalexandre/bandicoot/blob/a933fbd383cb7d6151c8a9ddf35ef1d5194efe53/bandicoot/io.py#L118) in the same file:

    elif 'place_id' in data:
            raise NameError("Use field name 'antenna_id' in input files. 'place_id' is deprecated.")

So in the antennas file, you want us to use `place_id` in the header, but in the records file you want us to use `antennas_id`. In the example in the [docs](http://bandicoot.mit.edu/docs/quickstart.html), your header for the antennas file uses `antennas_id` as a field.

Should `place_id` be replaced by `antennas_id` everywhere?

**Comment by PiranjaF** [comment]
Thanks for making us aware of that! Yes, `place_id` should be replaced by `antenna_id`. I've uploaded a fix to the develop branch.
