### ISSUE TITLE
Bandicoot app generates metadata.csv

### ISSUE THREAD

**Issue by matinte** [yvesalexandre/bandicoot#13]
Hi there,
I've trying bandicoot app and documentation, it looks really impressive. Nevertherless, I've been able to create metadata.csv file with my own mobile phone call/text data but antennas information is missing (antenna_id column is empty). 
Any idea why is happening this?

Thanks in advance

**Comment by cynddl** [comment]
Hi @matinte, thanks for your support!

Android does not log GPS locations, nor cell towers associated with calls or texts. So it's not possible to access previous locations using the bandicoot app.

However, we have experimental support for methods to merge high-resolution locations (eg. Google Location History) with your call and text metadata. This could be a little slow as bandicoot tries to aggregate thousands of location points. See http://bandicoot.mit.edu/docs/reference/bandicoot.others.html#helper-stops for more details.

**Comment by matinte** [comment]
Hi Luc,
Thanks for your response!
I've already downloaded a copy of my Google History Location in JSON. I
guess I should use Google History Records first.
For example:

# transform json to csv
df=pd.read_json("records/history.json")
df.to_csv('records/history.csv')

# then read 'my_user' data generated with bandicoot app
U = bc.read_csv('my_user', 'records/', 'user.csv', describe=False)
# and google history data
G = bc.read_csv('history', 'records/', 'history.csv', describe=False)

My question here is how should I use Google History Location data? First on
cluster_and_update() method with User or Google records?
# use history records or google records??
import bandicoot.helper.stops
bc.helper.stops.cluster_and_update({U,G}.records, max_elapsed_seconds=300)

Thanks again


2017-03-07 13:48 GMT+01:00 Luc Rocher <notifications@github.com>:
