### ISSUE TITLE
Backporting from Python 3 to Python 2.6

### ISSUE THREAD

**Issue by Sophia-Lazraq** [yvesalexandre/bandicoot#14]
I am working on a cluster which only supports Python 2.6.6  and bandicoot is coded in python 3 . 

I was wondering whether it is more efficient to change some parts and do backports or take the old bandicoot version (2.6) and add the new indicators I need for my model (present in the new bandicoot version, not the old one). Could you please tell me which option seems the most suitable ? I would really appreciate.

**Comment by cynddl** [comment]
Please have a look at https://github.com/yvesalexandre/bandicoot/tree/backport26. Most of the tests are now passing (48 passing, 8 failing).

I used Python 2.6.9, numpy 1.10, scipy 0.12, and networkx 1.9. to run the tests.
