### ISSUE TITLE
Is there a way to change the default weekend days (6 & 7)?

### ISSUE THREAD

**Issue by fabianbruckschen** [yvesalexandre/bandicoot#16]
First of all, this is a great python module, so thank you.
In my case I want to apply it (in particular the bc.utils.all function) to a muslim country. It all works fine, besides the fact that the weekend is actually on Friday and Saturday (so day [5,6] and not [6,7]). Is there an easy way to integrate it into the function?
Thanks in advance
fabibru

**Comment by cynddl** [comment]
Hello @fabianbruckschen, and thanks for your interest in bandicoot. There is indeed a per-user option to change the default weekend days:
https://github.com/yvesalexandre/bandicoot/blob/b26cfb05568ab762b93ad5efef8eebd099b7e9b5/bandicoot/core.py#L178

--------

Once you have a user object (eg. ```my_user = bc.test.sample_user()```, you can set:
```python
my_user.weekend = [5, 6]  # instead of [6, 7]
```

to change the default weekend days.

**Comment by fabianbruckschen** [comment]
Hi @cynddl,
thank you very much for this fast answer and simple solution by altering the user object.
Keep up the good work.
