### ISSUE TITLE
parse recharge date time format error

### ISSUE THREAD

**Issue by jiaxunsongucb** [yvesalexandre/bandicoot#17]
The recharge parsing function in io.py, line 191 "%Y-%m-%d" should be like "%Y-%m-%d %H:%M:%S", otherwise, the datetime cannot be loaded correctly. Or, all the recharge will be categorized in xxx_recharges__xxx__**night**__xxx because the time will be automatically encoded as midnight.

```python
def _parse_recharge(data):
    dt = _tryto(lambda x: datetime.strptime(x, "%Y-%m-%d"),
                data['datetime'])
```

**Comment by cynddl** [comment]
Thanks for opening this issue! Recharges can indeed include time and not only date. This issue has been fixed in f7cc04d, we're now loading either _date_ either _datetime_ entries automatically.

Please reopen this issue if it still doesn't work on your side.
