### ISSUE TITLE
average recharge balance error when the first and last recharge on the same day

### ISSUE THREAD

**Issue by jiaxunsongucb** [yvesalexandre/bandicoot#18]
The average_balance_recharges in recharge.py, line 89.
```python
return balance / (last_recharge.datetime - first_recharge.datetime).days
```
If the first and last recharge happen on the same day, the denominator will be 0. Maybe the denominator should plus 1, like this:
```python
return balance / ((last_recharge.datetime - first_recharge.datetime).days + 1)
```

**Comment by cynddl** [comment]
Thanks! This has been fixed in 73a658f. Let me know if that works as intended.
