### ISSUE TITLE
Integer division bug in great circle distance calculation

### ISSUE THREAD

**Issue by chrisjbrooks** [yvesalexandre/bandicoot#2]
Simple bug in `bandicoot/helper/tools.py` on lines [326](https://github.com/yvesalexandre/bandicoot/blob/a933fbd383cb7d6151c8a9ddf35ef1d5194efe53/bandicoot/helper/tools.py#L326) to [329](https://github.com/yvesalexandre/bandicoot/blob/a933fbd383cb7d6151c8a9ddf35ef1d5194efe53/bandicoot/helper/tools.py#L329) where `/` is integer division assuming both operands are `int`, which isn't usually the case. Fix by enforcing `pt1` and `pt2` to be `float`.

Probably doesn't affect normal use (as location points won't usually be `int`), but looks like this has led to incorrect test conditions in `bandicoot/tests/test_utils.py` on lines [77](https://github.com/yvesalexandre/bandicoot/blob/a933fbd383cb7d6151c8a9ddf35ef1d5194efe53/bandicoot/tests/test_utils.py#L77) to [82](https://github.com/yvesalexandre/bandicoot/blob/a933fbd383cb7d6151c8a9ddf35ef1d5194efe53/bandicoot/tests/test_utils.py#L82) since all the test points are `int`.

**Comment by cynddl** [comment]
Thanks for reporting this issue. Indeed, we should use a floating-point division in ``great_circle_distance``. Fortunately, ``Position`` objects don't use integers, but it's probably why we didn't catch this one.

**Comment by cynddl** [comment]
Fixed in the ``develop`` branch by 21295b1 and 4bf8666.
