### ISSUE TITLE
Exporting and visualising ego network visualisation

### ISSUE THREAD

**Issue by gaswani** [yvesalexandre/bandicoot#23]
@yvesalexandre 
Why is Iframe in the code block below not showing?
import os
# Export the visualization to a new directory, "viz".
bc.visualization.export(U, "GA")

Successfully exported the visualization to GA
'GA'

# Display the exported visualization in a frame within this notebook
IFrame("GA/index.html", '100%', 700)

This code block is also not showing the ego network:
import os
viz_path = os.path.dirname(os.path.realpath(__name__)) + '/viz'
bc.visualization.export(U, viz_path)

from IPython.display import IFrame
IFrame("/files/viz/index.html", "100%", 700)

Someone please help

**Comment by cynddl** [comment]
Hi @gaswani, I'm not sure I understand the issue.

You can also check the documentation at https://bandicoot.media.mit.edu/docs/quickstart.html#visualizing-a-user

**Comment by gaswani** [comment]
Hi @cynddl see a screenshot of my code attached. Output 9 is blank when I run Input 9. Why is there no output? Thanks for your help
<img width="1757" alt="Screenshot 2020-03-19 at 20 56 36" src="https://user-images.githubusercontent.com/39372384/77099803-a010a100-6a25-11ea-80be-55b400401261.png">
