### ISSUE TITLE
antennas' locations not loading?

### ISSUE THREAD

**Issue by samuelheroy** [yvesalexandre/bandicoot#24]
Hello,
I am trying to compute indicators for a user and have put calls/antennas into the format listed in the quick start docs. Here is the antennas file
<img width="645" alt="image" src="https://user-images.githubusercontent.com/9648979/77061306-efc57d00-69d1-11ea-800d-6776019bd155.png">
For some reason I can't pin down, these antennas' locations are not recognized.
<img width="531" alt="image" src="https://user-images.githubusercontent.com/9648979/77061393-108dd280-69d2-11ea-81ba-b1beaea241d4.png">
When I query the antennas, I still see there are attributes however:
<img width="328" alt="image" src="https://user-images.githubusercontent.com/9648979/77061490-374c0900-69d2-11ea-9127-27ec3ebcac48.png">
Any idea what might be happening here?

**Comment by cynddl** [comment]
Hi @samuelheroy, thanks for using bandicoot! Can you share a minimal reproducible example with the CSV for the user you consider? It might just be that the _antenna_id_ field does not match ids in your list of antennas.

**Comment by samuelheroy** [comment]
Sorry, I've fixed it. The samples I was using had decimal values (e.g. 2367.0) for antennas and non-decimal values (2367) in the antennas file. Should have checked this before
