### ISSUE TITLE
About the correspondent_id

### ISSUE THREAD

**Issue by cgarciae** [yvesalexandre/bandicoot#3]
Hi. I am trying to use Bandicoot to analyze Wifi data usage, the problem is very similar so the mapping between variables is easy. I am confused by the `correspondent_id` field on the `.csv`. On the getting started you start by loading `/data/records/A.csv` and state

> bandicoot uses one record file per user. Record files are structured as follows:

From this I inferred that all the data in `A.csv` is about user `A`. When looking at `correspondant_id` at first I assumed that it was the id of the user, but now I come to realize that it doesn't make sense since in [this](https://github.com/yvesalexandre/bandicoot/blob/master/demo/data/A.csv) example you see different `correspondante_id`'s, but they should all be the same if the data is about the same user.

So... what is really correspondent_id?

**Comment by brian717** [comment]
Hi, and thanks for the question. 

The correspondent_id is a unique identifier for the people the given user corresponds with. It is typically a hash of that person's phone number.

That example file contains correspondences (in this case, phone calls and text messages) for the given user. You can think of this file as a call log that also contains text message metadata as well. The correspondent_id is the user on the other end of the phone call or text message (either the initiator or the recipient of the correspondence).

For a row with an "out" in the direction column, the correspondent_id is the person who the user texted or called. Likewise, for a row with an "in" in the direction column, the correspondent_id is the person who called or texted the user who owns that file. 

Does this clear things up?

**Comment by cgarciae** [comment]
@brian717 

Thanks for the info! Is there a special reason why you didn't modeled the problem more like a directed graph? Say having `sender_id` and `receiver_id` on a single file, because I imagen that if you have users `A` and `B` then you need to have two files, and on each file duplicate information about their interaction. Is this right?

Would you be so kind as to give me some advice on how to map the problem into Bandicoots domain? The thing with wifi data is that you don't have correspondence between users, you just have users that receive data from some `cells`. Mapping cells to antennas is trivial since they both have locations, but users don't *interact* through wifi (they don't send each other wifi) so I don't know what to put in `correspondence_id`.  I am leaving it out. How will this affect bandicoots indicators?

Thanks a lot for your time!

**Comment by cynddl** [comment]
_bandicoot_ indicators are indeed derived from a theoretical graph connecting users. There are multiple ways to encode such data sets, including one file per user with or without duplicates, one large database…

The current approach is easy to implement and use. We don't need to look for files of every correspondant, and run into errors when files are missing, not encoded properly, _etc._

We tried from the beginning to ensure a good separation of concerns. The ``User`` and ``Record`` objects and the code for indicators are independ from the format of input data. You can plug with _bandicoot_ any graph database, or a Hadoop cluster, if you need. The documentation is not the best, but have a look at [bandicoot.io.load](bandicoot.mit.edu/docs/reference/generated/bandicoot.io.load.html) ([code](https://github.com/yvesalexandre/bandicoot/blob/master/bandicoot/io.py#L187)), the low-level function to create a user from records. It mostly takes a list of records,  check for consistency, and return a `User` object.

--------

About wifi data, we have a solution coming soon. We are implementing a solution to load not only calls and texts but also gps locations. The code is in the develop branch but subject to change in the next two weeks.

The future implementation will let you load sets of locations with date and time, cluster and label them using a [DBSCAN algorithm](https://en.wikipedia.org/wiki/DBSCAN) if needed, and compute spatial indicators. It should be released soon!
