### ISSUE TITLE
Graphing Functionalities Missing Docs

### ISSUE THREAD

**Issue by cgarciae** [yvesalexandre/bandicoot#4]
I saw the demo in the notebook but I can't find documentation on the graphing functionalities. I wrote same code as the demo but with my data and the `index.html`'s are not being generated after I run these lines

> bc.special.demo.export_antennas(U, 'viz/mobility_view')
bc.special.demo.export_transitions(U, 'viz/mobility_view') 
bc.special.demo.export_timeline(U, 'viz/event_timeline')
bc.special.demo.export_network(U, 'viz/network_view')

I did create those folders because I was getting errors. But now there are no errors but also no graphics. I'd appreciate help with this :)

**Comment by cgarciae** [comment]
I do notice the user has `[ ] No Network` which is different from what I see in the demo.

> [x] 1 record from 2015-11-30 00:40:29 to 2015-11-30 00:40:29
[x] 1 contact
[ ] No attribute stored
[x] 20597 antennas
[x] Has home
[ ] No texts
[x] Has calls
[ ] No network

**Comment by yvesalexandre** [comment]
Yes, the issue with the viz is legacy code that we need to fix. Sorry about that. We'll have a patch in the development branch in two weeks. I'll ping you then.

**Comment by cynddl** [comment]
Hey @cgarciae, we now have a visualization dashboard available in the develop branch. You can have a look at the `bandicoot.special.dashboard` module:

```python
# To serve an interactive dashboard:
bc.special.dashboard.server(my_user)
# Or to build it to a temp folder:
bc.special.dashboard.build(my_user)
```

Please tell us what you think about it! It's still an preliminary version, and we have many ideas to improve it. We currently haven't implemented location graphs, but we're thinking about it.

----

Here is what the dashboard looks like on Google Chrome. You can navigate through time and select indicators to visualize them:

![bandicoot-dashboard](https://cloud.githubusercontent.com/assets/847215/14648339/18b0e5a6-0662-11e6-8f10-4acdf8fbc14d.png)

**Comment by cgarciae** [comment]
@cynddl Looks incredible! I'll check it out.

**Comment by cynddl** [comment]
The visualization is now included and documented in the master branch.
