### ISSUE TITLE
´load_csv()´ does not report overlapping calls percentage, it shows format str instead ´{0:.2%}´ 

### ISSUE THREAD

**Issue by yellowBirdy** [yvesalexandre/bandicoot#5]
After loading a file with overlapping values I'm getting warnings like below:

´WARNING:root:{0:.2%} of calls overlap the next call by more than 5 minutes.´

**Comment by cynddl** [comment]
Fixed in 2c58d7c0cb4e931ff82e38191f79d168d1fcb3d8. Thanks for the report!
