### ISSUE TITLE
bc.read_csv() drop_duplicates option not working

### ISSUE THREAD

**Issue by yellowBirdy** [yvesalexandre/bandicoot#6]
`errors = bc.read_csv(error_user_id, records_with_errors_path, drop_duplicates=True)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-36-61a2b0bf2261> in <module>()
----> 1 errors = bc.read_csv(error_user_id, records_with_errors_path, drop_duplicates=True)

TypeError: read_csv() got an unexpected keyword argument 'drop_duplicates'`

**Comment by cynddl** [comment]
Fixed in dc505a9. Indeed, the ``drop_duplicates`` keyword was implemented in the low-level ``bc.io.load`` function, but not in ``bc.io.read_csv``. Thanks!
